export const Watches = {
  "BOLD ROUND ANALOG GUNMETAL DIAL": {
    price: "500.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX"],
    tags: ["DIGITAL", "SPORT"],
    description:
      "The Grand Camel is a timepiece designed to suit the masculine and confident man because of its combination of thick yet smooth cognac coated calf leather, the stainless steel case and hands.",
    brand: "gucci",
    Manufacturer: "USA",
    Color: ["brown"],
    Movement: "Automatic",
    "Strap Material": "Black Crocodile",
    "Water Resistance": "yes",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Bold-Round-Analog-Gunmetal-Dial-1-300x300.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Bold-Round-Analog-Gunmetal-Dial-1.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Bold-Round-Analog-Gunmetal-Dial-3.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Bold-Round-Analog-Gunmetal-Dial-2.jpg",
      ],
    },
  },
  "DAPPER ROUND ANALOG": {
    price: "87.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX"],
    tags: ["LADIES", "SALE"],
    brand: "Sonata",
    Manufacturer: "France",
    Color: ["black", "gold"],
    Movement: "Automatic",
    "Strap Material": "Brown Crocodile",
    Display: "Digital",
    "Water Resistance": "yes",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Dapper-Round-Analog-300x300.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Dapper-Round-Analog.jpg",
      ],
    },
  },
  "ROUND ANALOG WHITE & BEE DIAL LADIES": {
    price: "75.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS", "ROLEX"],
    tags: ["GOLD", "WATCH"],
    brand: "Tissot",
    Manufacturer: "USA",
    Color: ["black", "gold"],
    Movement: "Automatic",
    "Strap Material": "Calf Leather",
    Display: "Analog and Digital",
    "Water Resistance": "yes",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Bee-Dial-Ladies-2-300x300.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Bee-Dial-Ladies-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Bee-Dial-Ladies-3.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Bee-Dial-Ladies-1.jpg",
      ],
    },
  },
  "ROUND ANALOG WHITE DIAL LADIES": {
    price: "80.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX", "SMART WATCHS"],
    tags: ["DIGITAL", "GOLD"],
    brand: "Tom Ford",
    Manufacturer: "USA",
    Color: ["black", "gold"],
    Movement: "Automatic",
    "Strap Material": "Black Crocodile",
    Display: "Analog and Digital",
    "Water Resistance": "yes",
    "Alarm Clock": "no",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Dial-Ladies-2-300x300.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Dial-Ladies-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Dial-Ladies-3.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Round-Analog-White-Dial-Ladies-1.jpg",
      ],
    },
  },
  "THE RUNWELL SPORT CHRONO": {
    price: "190.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS"],
    tags: ["ANALOG", "DIGITAL", "NEW"],
    brand: "Sonata",
    Color: ["black", "gold", "silver"],
    Movement: "Automatic",
    "Strap Material": "Black Crocodile",
    Display: "Binary",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-SilverGold-2-300x300.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-SilverGold-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-SilverGold-4.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-SilverGold-3.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-SilverGold-1.jpg",
      ],
    },
    "Alarm Clock": "yes",
  },
  "TATUM ROUND ANALOG BLUE DIAL LADIES": {
    price: "87.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX"],
    tags: ["NEW", "WATCH"],
    brand: "Casio",
    Manufacturer: "Italy",
    Color: ["blue", "gold"],
    Movement: "Eco-Drive",
    "Strap Material": "Black Crocodile",
    Display: "Binary",
    "Water Resistance": "no",
    "Alarm Clock": "no",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Tatum-Round-Analog-Blue-Dial-Ladies-300x300.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/Tatum-Round-Analog-Blue-Dial-Ladies.jpg",
      ],
    },
    "Alarm Clock": "yes",
  },
  "THE RUNWELL SPORT CHRONO SILVER": {
    price: "240.00",
    categories: ["FOR HIM", "ROLEX", "SMART WATCHES"],
    tags: ["NEW", "WATCH"],
    brand: "Sonata",
    Manufacturer: "USA",
    Color: ["blue", "gold"],
    Movement: "Mechanical",
    "Strap Material": "Calf Leather",
    Display: "Digital",
    "Water Resistance": "no",
    "Alarm Clock": "no",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-2.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO-1.jpg",
      ],
    },
  },
  "THE BEDROCK CHRONO": {
    price: "122.00",
    categories: ["FOR HIM", "FOR KIDS", "ROLEX"],
    tags: ["LEATHER", "WATCH"],
    brand: "Casio",
    Color: ["brown"],
    Movement: "Mechanical",
    "Strap Material": "Black Crocodile",
    Display: "Binary",
    "Alarm Clock": "yes",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-BEDROCK-CHRONO-2.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-BEDROCK-CHRONO-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-BEDROCK-CHRONO-3.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-BEDROCK-CHRONO-1.jpg",
      ],
    },
  },
  "THE CANFIELD SPORT": {
    price: "454.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS", "SMART WATCHES"],
    tags: ["ANALOG", "SPORT"],
    brand: "Gucci",
    Manufacturer: "France",
    Color: ["black", "brown"],
    "Water Resistance": "yes",
    Movement: "Automatic",
    "Strap Material": "Brown Crocodile",
    "Alarm Clock": "yes",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-CANFIELD-SPORT-2.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-CANFIELD-SPORT-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-CANFIELD-SPORT-1.jpg",
      ],
    },
  },
  "THE LAKE MICHIGAN MONSTER": {
    price: "188.00",
    categories: ["FOR HIM", "FOR KIDS", "ROLEX", "SMART WATCHES"],
    tags: ["ANALOG", "NEW"],
    brand: "Tom Ford",
    Manufacturer: "Italy",
    Display: "Analog and Digital",
    Movement: "Mechanical",
    "Strap Material": "Aluminum",
    "Alarm Clock": "yes",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-LAKE-MICHIGAN-MONSTER-2.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-LAKE-MICHIGAN-MONSTER-2.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-LAKE-MICHIGAN-MONSTER-1.jpg",
      ],
    },
  },
  "THE LAKE MICHIGAN MONSTER BLACK": {
    price: "170.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS", "ROLEX", "SMART WATCHES"],
    tags: ["DIGITAL", "SALE"],
    brand: "Tissot",
    Manufacturer: "France",
    Movement: "Eco-Drive",
    "Strap Material": "Aluminum",
    "Alarm Clock": "yes",
    color: "black",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-LAKE-MICHIGAN-MONSTER-3.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-LAKE-MICHIGAN-MONSTER-3.jpg",
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-LAKE-MICHIGAN-MONSTER-4.jpg",
      ],
    },
  },
  "THE RUNWELL SPORT": {
    price: "365.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS", "ROLEX", "SMART WATCHES"],
    tags: ["LEATHER", "NEW", "SALE", "WATCH"],
    brand: "Cartier",
    Display: "Analog",
    Manufacturer: "France",
    Movement: "Auto-Quartz",
    "Alarm Clock": "no",
    "Water Resistance": "yes",
    color: "black",
    src: {
      main: "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO.jpg",
      slider: [
        "https://ld-wp73.template-help.com/woostroid2/skins/watchstore/wp-content/uploads/2019/06/THE-RUNWELL-SPORT-CHRONO.jpg",
      ],
    },
  },
};
