export const Watches = {
  "BOLD ROUND ANALOG GUNMETAL DIAL": {
    price: "500.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX"],
    tags: ["DIGITAL", "SPORT"],
    description:
      "The Grand Camel is a timepiece designed to suit the masculine and confident man because of its combination of thick yet smooth cognac coated calf leather, the stainless steel case and hands.",
    brand: "gucci",
    Manufacturer: "USA",
    Color: ["brown"],
    Movement: "Automatic",
    "Strap Material": "Black Crocodile",
    "Water Resistance": "yes",
    src: {
      main: "src/assets/Bold-Round-Analog-Gunmetal-Dial-1-300x300.jpg",
      slider: [
        "../src/assets/item1/Bold-Round-Analog-Gunmetal-Dial-1.jpg",
        "../src/assets/item1/Bold-Round-Analog-Gunmetal-Dial-2.jpg",
        "../src/assets/item1/Bold-Round-Analog-Gunmetal-Dial-3.jpg",
      ],
    },
  },
  "DAPPER ROUND ANALOG": {
    price: "87.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX"],
    tags: ["LADIES", "SALE"],
    brand: "Sonata",
    Manufacturer: "France",
    Color: ["black", "gold"],
    Movement: "Automatic",
    "Strap Material": "Brown Crocodile",
    Display: "Digital",
    "Water Resistance": "yes",
    src: {
      main: "src/assets/Dapper-Round-Analog-300x300.jpg",
    },
  },
  "ROUND ANALOG WHITE & BEE DIAL LADIES": {
    price: "75.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS", "ROLEX"],
    tags: ["GOLD", "WATCH"],
    brand: "Tissot",
    Manufacturer: "USA",
    Color: ["black", "gold"],
    Movement: "Automatic",
    "Strap Material": "Calf Leather",
    Display: "Analog and Digital",
    "Water Resistance": "yes",
    src: {
      main: "src/assets/Round-Analog-White-Bee-Dial-Ladies-2-300x300.jpg",
    },
  },
  "ROUND ANALOG WHITE DIAL LADIES": {
    price: "80.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX", "SMART WATCHS"],
    tags: ["DIGITAL", "GOLD"],
    brand: "Tom Ford",
    Manufacturer: "USA",
    Color: ["black", "gold"],
    Movement: "Automatic",
    "Strap Material": "Black Crocodile",
    Display: "Analog and Digital",
    "Water Resistance": "yes",
    "Alarm Clock": "no",
    src: {
      main: "src/assets/Round-Analog-White-Dial-Ladies-2-300x300.jpg",
    },
  },
  "THE RUNWELL SPORT CHRONO": {
    price: "190.00",
    categories: ["FOR HER", "FOR HIM", "FOR KIDS"],
    tags: ["ANALOG", "DIGITAL", "NEW"],
    brand: "Sonata",
    Color: ["black", "gold", "silver"],
    Movement: "Automatic",
    "Strap Material": "Black Crocodile",
    Display: "Binary",
    "Water Resistance": "yes",
    "Alarm Clock": "no",
    src: {
      main: "src/assets/THE-RUNWELL-SPORT-CHRONO-SilverGold-2-300x300.jpg",
    },
    "Alarm Clock": "yes",
  },
  "TATUM ROUND ANALOG BLUE DIAL LADIES": {
    price: "87.00",
    categories: ["FOR HER", "FOR HIM", "ROLEX"],
    tags: ["NEW", "WATCH"],
    brand: "Casio",
    Manufacturer: "Italy",
    Color: ["BLUE", "gold"],
    Movement: "Eco-Drive",
    "Strap Material": "Black Crocodile",
    Display: "Binary",
    "Water Resistance": "yes",
    "Alarm Clock": "no",
    src: {
      main: "src/assets/Tatum-Round-Analog-Blue-Dial-Ladies-300x300.jpg",
    },
    "Alarm Clock": "yes",
    "Water Resistance": "no",
  },
};
